services:
  - type: web
    name: chat-app
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    numInstances: 1
    plan: free
